let bandasDeRock = [
    {
        titulo: "Metallica",
        descrição: "Pioneiros do thrash metal, com um som pesado e agressivo.",
        link: "https://pt.wikipedia.org/wiki/Metallica",
        tags:"rock heavy metal thrash metal",
      },
      {
        titulo: "Queen",
        descrição: "Banda de rock britânica conhecida por sua música ecléctica e performances extravagantes.",
        link: "https://pt.wikipedia.org/wiki/Queen",
        tags:"rock metal europa",
      },
      {
        titulo: "Black Sabbath",
        descrição: "Considerados os pais do heavy metal, com um som dark e influente.",
        link: "https://pt.wikipedia.org/wiki/Black_Sabbath",
        tags:"rock dark metal",
      },
      {
        titulo: "The Rolling Stones",
        descrição: "Uma das bandas de rock mais antigas e influentes, com um som bluesy e letras provocativas.",
        link: "https://pt.wikipedia.org/wiki/The_Rolling_Stones",
        tags:"rock bluesy metal",
      },
      {
        titulo: "Nirvana",
        descrição: "Ícones do grunge, com um som pesado e letras introspectivas.",
        link: "https://pt.wikipedia.org/wiki/Nirvana",
        tags:"rock brunge pesado metal",
      },
      {
        titulo: "Pink Floyd",
        descrição: "Conhecidos por seus álbuns conceituais e experimentações sonoras.",
        link: "https://pt.wikipedia.org/wiki/Pink Floyd",
        tags:"rock heavy metal",
      },
      {
        titulo: "Led Zeppelin",
        descrição: "Pioneiros do heavy metal, com um som poderoso e influente.",
        link: "https://pt.wikipedia.org/wiki/Led_Zeppelin",
        tags:"rock heavy metal ",
      },
      {
        titulo: "AC/DC",
        descrição: "Banda australiana de hard rock, conhecida por seus riffs poderosos e shows energéticos.",
        link: "https://pt.wikipedia.org/wiki/AC/DC",
        tags:"rock riffs metal australia",
      },
      {
        titulo: "Aerosmith",
        descrição: "Uma das bandas de hard rock mais populares dos Estados Unidos, com um som bluesy e melodias marcantes.",
        link: "https://pt.wikipedia.org/wiki/Aerosmith",
        tags:" hard metal eua estados unidos",
      },
      {
        titulo: "Deep Purple",
        descrição: "Pioneiros do hard rock e heavy metal, com um som poderoso e progressivo.",
        link: "https://pt.wikipedia.org/wiki/Deep_Purple",
        tags:"rock hard metal progressivo",
      },
      {
        titulo: "The Doors",
        descrição: "Banda psicodélica americana, liderada por Jim Morrison, com um som experimental e letras poéticas.",
        link: "https://pt.wikipedia.org/wiki/The_Doors",
        tags:"rock heavy eua estados unidos ",
      },
      {
        titulo: "Jimi Hendrix",
        descrição: "Considerado um dos maiores guitarristas de todos os tempos, com um estilo inovador e influente.",
        link: "https://pt.wikipedia.org/wiki/Jimi_Hendrix",
        tags:"rock guitarra guitarrista",
      },
      {
        titulo: "Radiohead",
        descrição: "Banda de rock alternativo britânica, conhecida por suas experimentações sonoras e letras introspectivas.",
        link: "https://pt.wikipedia.org/wiki/Radiohead",
        tags:"rock alternativo metal europa",
      },
      {
        titulo: "U2",
        descrição: "Banda de rock irlandesa, com um som pop rock e mensagens de esperança e positividade.",
        link: "https://pt.wikipedia.org/wiki/U2",
        tags:"rock irlanda pop ",
      },
      {
        titulo: "Red Hot Chili Peppers",
        descrição: "Banda de funk rock americana, conhecida por suas performances energéticas e letras irreverentes.",
        link: "https://pt.wikipedia.org/wiki/Red_Hot_Chili_Peppers",
        tags:"rock estados unidos eua funk",
      },
      {
        titulo: "Guns N' Roses",
        descrição: "Banda de hard rock americana, conhecida por seus álbuns de estreia e por suas performances ao vivo.",
        link: "https://pt.wikipedia.org/wiki/Guns_N'_Roses",
        tags:"rock eua estados unidos",
      },
      {
        titulo: "Slayer",
        descrição: "Uma das bandas mais importantes do thrash metal, com um som extremamente agressivo e letras sombrias.",
        link: "https://pt.wikipedia.org/wiki/Slayer",
        tags:"rock heavy thrash metal",
      },
      {
        titulo: "Megadeth",
        descrição: "Uma das bandas mais técnicas do thrash metal, com um som rápido e preciso.",
        link: "https://pt.wikipedia.org/wiki/Megadeth",
        tags:"rock rapido metal thrash",
      },
      {
        titulo: "Anthrax",
        descrição: "Uma das bandas mais comerciais do thrash metal, com um som mais acessível e influências do hardcore punk.",
        link: "https://pt.wikipedia.org/wiki/Anthrax",
        tags:" hardcore punk thrash metal",
      },
      {
        titulo: "The Who",
        descrição: "Banda de rock britânica, conhecida por suas performances enérgicas e álbuns conceituais.",
        link: "https://pt.wikipedia.org/wiki/The_Who",
        tags:"rock heavy metal thrash metal",
      },
      {
        titulo: "The Clash",
        descrição: "Uma das bandas mais importantes do punk rock, com um som cru e letras politicamente engajadas.",
        link: "https://pt.wikipedia.org/wiki/The_Clash",
        tags:"rock punk political thrash metal",
      },
      {
        titulo: "Ramones",
        descrição: "Considerados os pais do punk rock, com um som rápido, simples e direto.",
        link: "https://pt.wikipedia.org/wiki/Ramones",
        tags:"rock punk metal",
      },
      {
        titulo: "Sex Pistols",
        descrição: "Uma das bandas mais controversas e influentes do punk rock, com um som agressivo e letras provocativas.",
        link: "https://pt.wikipedia.org/wiki/Sex_Pistols",
        tags:"rock punk thrash ",
      },
      {
        titulo: "The Kinks",
        descrição: "Banda de rock britânica, conhecida por suas melodias cativantes e letras irônicas.",
        link: "https://pt.wikipedia.org/wiki/The_Kinks",
        tags:"rock metal europa",
      },
      {
        titulo: "Velvet Underground",
        descrição: "Considerados uma das bandas mais influentes do rock experimental, com um som inovador e letras provocativas.",
        link: "https://pt.wikipedia.org/wiki/Velvet_Underground",
        tags:"rock heavy experimental ",
      },
      {
        titulo: "The Beach Boys",
        descrição: "Banda americana de surf rock, conhecida por suas harmonias vocais e letras sobre a cultura californiana.",
        link: "https://pt.wikipedia.org/wiki/The_Beach_Boys",
        tags:" surf vocal eua estados unidos",
      },
      {
        titulo: "The Grateful Dead",
        descrição: "Banda americana de rock psicodélico, conhecida por seus shows improvisados e longas jam sessions.",
        link: "https://pt.wikipedia.org/wiki/The_Grateful_Dead",
        tags:"rock estados unidos eua",
      },
      {
        titulo: "Creedence Clearwater Revival",
        descrição: "Banda americana de rock, conhecida por suas canções com temática country e blues.",
        link: "https://pt.wikipedia.org/wiki/Creedence_Clearwater_Revival",
        tags:" country estados unidos eua blues",
      },
      {
        titulo: "Eagles",
        descrição: "Banda americana de country rock, com um som melódico e letras sobre a vida americana.",
        link: "https://pt.wikipedia.org/wiki/Eagles",
        tags:"country estados unidos eua blue",
      },
      {
        titulo: "Fleetwood Mac",
        descrição: "Banda de rock britânica, conhecida por suas baladas românticas e sucessos comerciais.",
        link: "https://pt.wikipedia.org/wiki/Fleetwood_Mac",
        tags:"country europa balada",
      },
      {
        titulo: "Van Halen",
        descrição: "Banda de hard rock americana, conhecida pelo talento de Eddie Van Halen na guitarra e por seus shows explosivos.",
        link: "https://pt.wikipedia.org/wiki/Van_Halen",
        tags:" hard rock eua estados unidos",
      },
      {
        titulo: "Rush",
        descrição: "Banda canadense de rock progressivo, conhecida por suas composições complexas e letras inteligentes.",
        link: "https://pt.wikipedia.org/wiki/Rush",
        tags:"progressivo canada rock",
      },
      {
        titulo: "Yes",
        descrição: "Uma das bandas mais importantes do rock progressivo, com um som complexo e melodioso.",
        link: "https://pt.wikipedia.org/wiki/Yes",
        tags:"progressivo melodico rock",
      },
];

 